version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: week3
      POSTGRES_USER: phatdev
      POSTGRES_PASSWORD: phatdev
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: